#! /bin/sh
### BEGIN INIT INFO
# Provides:          lcdops
# Required-Start:    librespot
# Required-Stop:
# Default-Start:     2 3
# Default-Stop: 0 6
# Short-Description: Start or stop librespot.
# Description:       Starts or stops the lcdops program
### END INIT INFO

LCDWORKSDIR=/opt/lcdworks
EXECNAME=lcdmanager.py
DAEMON=${LCDWORKSDIR}/bin/${EXECNAME}
DAEMON_OPTS="-f ${LCDWORKSDIR}/conf/lcdworks.conf"
[ -x "$DAEMON" ] || exit 0
NAME=lcdops
DESC="aldemir HiFi lcdops"
. /lib/init/vars.sh

. /lib/lsb/init-functions

case "$1" in
  start)
    #log_use_fancy_output
	log_daemon_msg "Starting $DESC" "$NAME"
    #start-stop-daemon --start --quiet --pidfile /var/run/$NAME --exec $DAEMON
    start-stop-daemon --start --exec $DAEMON -- $DAEMON_OPTS
	log_end_msg $?
	;;
  stop)
    log_use_fancy_output
	log_daemon_msg "Stopping $DESC" "$NAME"
	start-stop-daemon --stop --quiet --retry TERM/5/KILL/5 --pidfile /var/run/${EXECNAME}.pid
	log_end_msg $?
	;;
  restart|force-reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $SCRIPTNAME {start|stop|restart}" >&2
	exit 3
	;;
esac

:
